# This is a basic workflow to help you get started with Actions

name: push-build-check

# Controls when the workflow will run
on: push
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-windows-x86:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
    
      - name: install qt static
        uses: orestonce/install-qt@main
        with:
          version: Qt5.6.3-Windows-x86-MinGW4.9.4-staticFull-20200104
      - name: Setup Go environment
        uses: actions/setup-go@v3.2.1
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges.
          go-version: 1.18 # optional
      - name: build
        run: |
          go mod tidy
          go run export/main.go build-cli
          go run export/main.go create-qt-lib 386 c-archive
          cd m3u8d-qt && qmake && mingw32-make release && cd ..
          dir m3u8d-qt\release\m3u8d-qt.exe
  build-windows-x64:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: install qt static
        uses: orestonce/install-qt@main
        with:
          version: Qt5.15.7-Windows-x86_64-MinGW8.1.0-staticFull-20221104
      - name: Setup Go environment
        uses: actions/setup-go@v3.2.1
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges.
          go-version: 1.18 # optional
      - name: build
        run: |
          go mod tidy
          go run export/main.go create-qt-lib amd64 c-archive
          cd m3u8d-qt && qmake && mingw32-make release && cd ..
          dir m3u8d-qt\release\m3u8d-qt.exe
  build-macos-arm64:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: install qt
        uses: orestonce/install-qt@main
        with:
          version: Qt5.15.14-macOS-Universal-AppleClang15.0.0-noFramework-20240527
      - name: Setup Go environment
        uses: actions/setup-go@v3.2.1
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges.
          go-version: 1.18 # optional
      - name: build
        run: |
          set -x
          set -e
          go mod tidy
          go run export/main.go create-qt-lib arm64 c-shared
          cd m3u8d-qt && qmake && make && cd ..
          find . | grep -v qt_install 
          cd m3u8d-qt
          install_name_tool -change m3u8d-impl @executable_path/m3u8d-impl m3u8d-qt.app/Contents/MacOS/m3u8d-qt
          cp m3u8d-impl m3u8d-qt.app/Contents/MacOS/
          macdeployqt m3u8d-qt.app -dmg 
          ls -alh m3u8d-qt.dmg
  build-macos-amd64:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: install qt
        uses: orestonce/install-qt@main
        with:
          version: Qt5.15.6-macOS-x86_64-AppleClang12.0.5-noFramework-20220914
      - name: Setup Go environment
        uses: actions/setup-go@v3.2.1
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges.
          go-version: 1.18 # optional
      - name: build
        run: |
          set -x
          set -e
          go mod tidy
          go run export/main.go create-qt-lib amd64 c-shared
          pwd
          cd m3u8d-qt
          rm -f m3u8d-qt.pro.user
          pwd
          find `pwd`
          export QMAKE_XCODE_DEVELOPER_PATH="/Applications/Xcode.app/Contents/Developer"
          echo $QMAKE_XCODE_DEVELOPER_PATH
          find /Applications/Xcode.app/Contents/Developer
          qmake -project
          make
          pwd
          cd ..
          pwd
          find . | grep -v qt_install
#          cd m3u8d-qt
#          install_name_tool -change m3u8d-impl @executable_path/m3u8d-impl m3u8d-qt.app/Contents/MacOS/m3u8d-qt
#          cp m3u8d-impl m3u8d-qt.app/Contents/MacOS/
#          macdeployqt m3u8d-qt.app -dmg
#          ls -alh m3u8d-qt.dmg